services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: nexa_backend
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://nexa.tosun.nl
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: pgsql
      DB_HOST: 192.168.178.249
      DB_PORT: 5432
      DB_DATABASE: nexa
      DB_USERNAME: mtosun
      DB_PASSWORD: ${DB_PASSWORD}     # inject via runner/host env of .env naast compose

      N8N_URL: https://n8n.tosun.nl
      N8N_PORT: "5678"
      N8N_EMAIL: m.tosun@mebura.nl
      N8N_PASSWORD: ${N8N_PASSWORD}   # idem

    volumes:
      - ./backend/storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
      - ./backend/public/build:/var/www/html/public/build
      - ./.env:/var/www/html/.env  # .env file uit root naar container
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "php", "-r", "exit((int)!@fsockopen('127.0.0.1',8000));"]
      interval: 10s
      timeout: 3s
      retries: 10
